// services/atcExplain.service.js
// Human-readable descriptions for ATC codes. atcMap.json (generated by scripts/buildAtcMap.js)
// holds official WHO class names for every code referenced by ingredientCodes.json plus their
// 1/3/4-char prefixes. atcCurated.json is a hand-written overlay of patient-friendly labels and
// "commonly used for" bullets, keyed by code of any length; longest-prefix match wins.
//
// Codes in this dataset are 5-char level-4 codes (e.g. "M01AB"); meaningful prefixes are 1/3/4.
const ATC_MAP = require("../data/atcMap.json");
const CURATED = require("../data/atcCurated.json");

const PREFIX_LENGTHS = [5, 4, 3, 1];

function clean(code) {
  return String(code || "").trim().toUpperCase();
}

// Official WHO name for a code, falling back through shorter prefixes.
function atcOfficialName(code) {
  const c = clean(code);
  for (const len of PREFIX_LENGTHS) {
    if (c.length < len) continue;
    const name = ATC_MAP[c.slice(0, len)];
    if (name) return name;
  }
  return null;
}

// Curated entry for a code (friendlyLabel + commonUses), longest-prefix-first.
function curatedFor(code) {
  const c = clean(code);
  for (const len of PREFIX_LENGTHS) {
    if (c.length < len) continue;
    const entry = CURATED[c.slice(0, len)];
    if (entry && entry.friendlyLabel) return entry;
  }
  return null;
}

// RxNorm gives ingredients ALL their WHO class memberships, including ragbag ("Other cardiac
// preparations" — ibuprofen, via neonatal use) and route-specific ones ("Topical products for
// joint pain", "…for vaginal administration"). Those are never the class a user means, so they
// lose ties against clean systemic classes.
const SIDE_CLASS = /\bother\b|various|combination|topical|vaginal|rectal|nasal|\blocal\b|throat|ophthalmolog|otolog/i;

// Pick the "primary" class for a set of codes (combination products span several classes):
// group by 3-char class; prefer curated classes, then classes with at least one non-ragbag
// code name, then the class with the most codes, then alphabetical.
function pickPrimaryCode(codes) {
  const cleaned = [...new Set(codes.map(clean).filter(Boolean))];
  if (!cleaned.length) return null;

  const byClass = new Map();
  for (const code of cleaned) {
    const key = code.slice(0, 3);
    if (!byClass.has(key)) byClass.set(key, []);
    byClass.get(key).push(code);
  }

  const isCleanClass = classCodes =>
    classCodes.some(c => !SIDE_CLASS.test(atcOfficialName(c) || "")) ? 1 : 0;

  const ranked = [...byClass.entries()].sort((a, b) => {
    const aClean = isCleanClass(a[1]);
    const bClean = isCleanClass(b[1]);
    if (aClean !== bClean) return bClean - aClean;
    const aCurated = CURATED[a[0]] ? 1 : 0;
    const bCurated = CURATED[b[0]] ? 1 : 0;
    if (aCurated !== bCurated) return bCurated - aCurated;
    if (a[1].length !== b[1].length) return b[1].length - a[1].length;
    return a[0].localeCompare(b[0]);
  });

  // Within the winning class, a clean-named code beats a ragbag one, then alphabetical.
  return ranked[0][1].sort((a, b) => {
    const aClean = SIDE_CLASS.test(atcOfficialName(a) || "") ? 1 : 0;
    const bClean = SIDE_CLASS.test(atcOfficialName(b) || "") ? 1 : 0;
    if (aClean !== bClean) return aClean - bClean;
    return a.localeCompare(b);
  })[0];
}

// Full description for a set of ATC codes. Null when nothing usable.
function describeAtc(codes) {
  const primaryCode = pickPrimaryCode(codes || []);
  if (!primaryCode) return null;

  const className = atcOfficialName(primaryCode);
  const curated = curatedFor(primaryCode);
  if (!className && !curated) return null;

  return {
    primaryCode,
    atc3: primaryCode.slice(0, 3),
    atc4: primaryCode.length >= 4 ? primaryCode.slice(0, 4) : null,
    className,
    friendlyLabel: curated?.friendlyLabel || className,
    commonUses: curated?.commonUses || []
  };
}

// One-liner for badges and similarity strings: curated label, else official class name.
function classLabel(codes) {
  const atc = describeAtc(codes);
  return atc ? atc.friendlyLabel : null;
}

module.exports = { atcOfficialName, describeAtc, classLabel };
